title: bluestreak collaborative
description: collaborations with Bonnie Aumann
theme: jekyll-theme-architect

gems:
    - jekyll-mentions
    - jemoji
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed
